site_name: resume Documentation
theme: 'material'
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: '#087da1'
    accent: '#00a889'
  font:
    text: 'Source Sans Pro'

repo_name: 'omarhermenegildo/resume'
repo_url: 'https://github.com/omarhermenegildo/resume'
copyright: 'Copyright © 2021 <a href="https://omarhermenegildo.github.io">omarhermenegildo</a>'

google_analytics:
  - ''
  - 'auto'
